
/*
 *  Copyright (c) 2025 Huawei Device Co., Ltd.
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

import {  TrainList,TrainListPage } from  "@safe/train"
@Entry
@Component
export  struct SecondView {
  pathStack: NavPathStack = AppStorage.get("pathStack") as NavPathStack
  build() {
    NavDestination(){
      Column(){
        Column() {
          TrainListPage({
            dataList:TrainList
          })
        }
      }
    }
    .title('在线培训')
  }
}

@Builder
export function SecondViewBuilder(){
  SecondView();
}