/*
 *  Copyright (c) 2025 Huawei Device Co., Ltd.
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

export { TrainPage } from './src/main/ets/pages/Index'

export { EmptyComponent } from './src/main/ets/view/Empty'

export { TrainListPage } from './src/main/ets/view/TrainListPage'

export { TrainInfo, TrainList } from './src/main/ets/viewmodel/TrainInfoModel'

export { NavInfo } from './src/main/ets/viewmodel/NavInfoModel'

export { TrainDetailPage } from './src/main/ets/pages/TrainDetailPage'

export { ExaminationDetailPage } from './src/main/ets/pages/ExaminationDetailPage'

export { CourseDetailPage } from './src/main/ets/pages/CourseDetailPage'

export { IdInfo } from './src/main/ets/viewmodel/NavInfoModel'