/*
 *  Copyright (c) 2025 Huawei Device Co., Ltd.
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

/**
 * Common constants for all features.
 */
export default class TrainConstants {
  static readonly FULL_WIDTH: string = '100%';
  static readonly FULL_HEIGHT: string = '100%';
  static readonly TOAST_INTERVAL_TIME: number = 1000;
  static readonly LIST_LANES_NUM: number = 2
  static readonly APP_LOGIN_PAGE_URL: string = 'pages/LoginPage';
  static readonly APP_REGISTER_PAGE_URL: string = 'pages/RegisterPage';
}