/*
 *  Copyright (c) 2025 Huawei Device Co., Ltd.
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

import { OnlineListModel } from './OnlineListModel'

export const onlineList: OnlineListModel[] = [
  new OnlineListModel(
    '您有一条行业模板消息，请准备查收',
    '1',
    '2024-05-20'
  ),
  new OnlineListModel(
    '您有一条行业模板消息，请准备查收',
    '2',
    '2024-05-20'
  ),
  new OnlineListModel(
    '您有一条行业模板消息，请准备查收',
    '3',
    '2024-05-20'
  ),
  new OnlineListModel(
    '您有一条行业模板消息，请准备查收',
    '1',
    '2024-05-20'
  ),
  new OnlineListModel(
    '您有一条行业模板消息，请准备查收',
    '4',
    '2024-05-20'
  ),
  new OnlineListModel(
    '您有一条行业模板消息，请准备查收',
    '5',
    '2024-05-20'
  ),
  new OnlineListModel(
    '您有一条行业模板消息，请准备查收',
    '6',
    '2024-05-20'
  ),
  new OnlineListModel(
    '您有一条行业模板消息，请准备查收',
    '7',
    '2024-05-20'
  ),
  new OnlineListModel(
    '您有一条行业模板消息，请准备查收',
    '8',
    '2024-05-20'
  ),
  new OnlineListModel(
    '您有一条行业模板消息，请准备查收',
    '9',
    '2024-05-20'
  ),
  new OnlineListModel(
    '您有一条行业模板消息，请准备查收',
    '10',
    '2024-05-20'
  ),
  new OnlineListModel(
    '您有一条行业模板消息，请准备查收',
    '11',
    '2024-05-20'
  ),
  new OnlineListModel(
    '您有一条行业模板消息，请准备查收',
    '12',
    '2024-05-20'
  ),
  new OnlineListModel(
    '您有一条行业模板消息，请准备查收',
    '13',
    '2024-05-20'
  ),
  new OnlineListModel(
    '您有一条行业模板消息，请准备查收',
    '14',
    '2024-05-20'
  ),
  new OnlineListModel(
    '您有一条行业模板消息，请准备查收',
    '15',
    '2024-05-20'
  ),
  new OnlineListModel(
    '您有一条行业模板消息，请准备查收',
    '16',
    '2024-05-20'
  ),
]